name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install awsebcli
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create .env file
        run: |
          cat > .env << EOF
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}
          EOF
      
      - name: Create Procfile
        run: |
          echo "web: gunicorn webapp:app" > Procfile
          
      - name: Create Elastic Beanstalk config
        run: |
          mkdir -p .ebextensions
          cat > .ebextensions/01_flask.config << EOF
          option_settings:
            aws:elasticbeanstalk:container:python:
              WSGIPath: webapp:app
            aws:elasticbeanstalk:application:environment:
              GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
              OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
              TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          EOF
      
      - name: Generate deployment package
        run: zip -r deploy.zip * -x "*.git*"
      
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: EducationAgentResearcher
          environment_name: EducationAgentResearcher-env
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}-${{ github.run_number }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 180