name: Deploy Flask App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install AWS CLI (Pinned Version)
        run: pip install awscli==1.38.4 --user

      - name: Install Elastic Beanstalk CLI (Pinned Version)
        run: pip install awsebcli==3.21.0 --user

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config

      - name: Recreate .env File from GitHub Secrets
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> .env

      - name: Initialize Elastic Beanstalk (If Needed)
        run: |
          if [ ! -d ".elasticbeanstalk" ]; then
            eb init -p python-3.12 EducationAgentResearcher --region ${{ secrets.AWS_REGION }}
          fi

      - name: Check if Environment Exists
        id: check_env
        run: |
          if aws elasticbeanstalk describe-environments --application-name EducationAgentResearcher --query "Environments[?EnvironmentName=='EducationAgentEnv'].EnvironmentName" --output text |
